name: build and deploy container

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  service:
    uses: kubernetes-mail-server/.github/.github/workflows/service.yml@main
    secrets: inherit
    with:
      name: rspamd
      helm-args: >-
        --set port_0=$(kubectl get cm -n mail-server services-info -o=jsonpath="{.data.RSPAMD_PORT_0}")
        --set port_1=$(kubectl get cm -n mail-server services-info -o=jsonpath="{.data.RSPAMD_PORT_1}")
        --set port_2=$(kubectl get cm -n mail-server services-info -o=jsonpath="{.data.RSPAMD_PORT_2}")
